export {default as AdminMenu} from './AdminMenu';
export {default as AddNews} from './AddNews';
export {default as ManageNews} from './ManageNews';
export {default as PendingDeposits} from './PendingDeposits';
export {default as PendingWithdrawals} from './PendingWithdrawals';
export {default as ShareProfit} from './ShareProfit';
export {default as ProfitHistory} from './ProfitHistory';
export {default as EditProcessors} from './EditProcessors';
export {default as ManageUsers} from './ManageUsers';